import { useState } from 'react'
import { ArrowLeft, Sparkles, ArrowRight, Briefcase, CheckCircle2, Linkedin, Download } from 'lucide-react'
import { Link } from 'react-router-dom'
import api from '../api/axios.js'
import toast from 'react-hot-toast'

export default function ArchitectPage() {
  const [prompt, setPrompt] = useState('')
  const [loading, setLoading] = useState(false)
  const [roadmap, setRoadmap] = useState(null)

  const generateSyllabus = async (e) => {
    e.preventDefault()
    if (!prompt.trim() || loading) return
    setLoading(true)
    setRoadmap(null)
    
    try {
      const { data } = await api.post('/architect', { prompt: prompt.trim() })
      if (Array.isArray(data.data) && data.data.length > 0) {
        setRoadmap(data.data)
      } else {
        toast.error('The Architect could not map this timeline.')
      }
    } catch (err) {
      toast.error(err.response?.data?.message || 'Connection to the Architect failed.')
    } finally {
      setLoading(false)
    }
  }

  const shareToLinkedIn = () => {
    if (!roadmap) return
    const steps = roadmap.map((s, i) => `${i + 1}. ${s.title} (${s.duration})`).join('\n')
    const text = `🚀 I just mapped my AI career path with NeuralPath!\n\nMy personalized learning roadmap for: "${prompt}"\n\n${steps}\n\n🔗 Built using NeuralPath AI Career Architect — neuralpath.in\n#AILearning #CareerGrowth #NeuralPath #TechCareer`
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent('https://neuralpath.in')}&summary=${encodeURIComponent(text)}`
    window.open(url, '_blank', 'noopener,noreferrer,width=600,height=600')
    toast.success('LinkedIn share window opened!', { icon: '🔗' })
  }

  const downloadTimeline = () => {
    if (!roadmap) return
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>NeuralPath Career Roadmap — ${prompt}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #111; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 2rem; margin-bottom: 0.3rem; color: #0a0a0a; }
    .subtitle { color: #666; margin-bottom: 2rem; font-size: 0.95rem; }
    .brand { display: flex; align-items: center; gap: 10px; margin-bottom: 2rem; }
    .brand-dot { width: 10px; height: 10px; border-radius: 50%; background: #06ffa5; display: inline-block; }
    .brand-name { font-weight: 800; font-size: 1.2rem; color: #0077b5; }
    .step { display: flex; gap: 1.5rem; margin-bottom: 2rem; align-items: flex-start; }
    .node { min-width: 52px; width: 52px; height: 52px; border-radius: 50%; border: 2px solid #0077b5; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 1.1rem; color: #0077b5; background: #f0f8ff; flex-shrink: 0; }
    .content { flex: 1; border: 1px solid #e5e7eb; border-radius: 12px; padding: 1.2rem 1.5rem; }
    .duration { font-size: 0.75rem; font-weight: 700; color: #888; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 0.5rem; }
    .title { font-size: 1.15rem; font-weight: 700; margin-bottom: 0.5rem; }
    .desc { color: #555; font-size: 0.9rem; line-height: 1.6; }
    .footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e5e7eb; text-align: center; color: #999; font-size: 0.8rem; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="brand"><span class="brand-dot"></span><span class="brand-name">NeuralPath</span></div>
  <h1>My AI Career Roadmap</h1>
  <p class="subtitle">Goal: ${prompt} &nbsp;|&nbsp; Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
  ${roadmap.map((s, i) => `
  <div class="step">
    <div class="node">${s.step || i + 1}</div>
    <div class="content">
      <div class="duration">${s.duration}</div>
      <div class="title">${s.title}</div>
      <div class="desc">${s.description}</div>
    </div>
  </div>`).join('')}
  <div class="footer">Generated by NeuralPath AI Career Architect &mdash; neuralpath.in &nbsp;&bull;&nbsp; Printed on ${new Date().toLocaleDateString()}</div>
</body>
</html>`
    const win = window.open('', '_blank')
    win.document.write(html)
    win.document.close()
    win.focus()
    setTimeout(() => { win.print() }, 500)
    toast.success('Print dialog opened — choose Save as PDF to download!', { icon: '📄', duration: 5000 })
  }

  return (
    <div style={{ minHeight: '100vh', paddingTop: '100px', paddingBottom: '80px', background: 'radial-gradient(circle at top, #081121 0%, #030712 100%)', position: 'relative', zIndex: 1 }}>
      
      {/* Navigation Escape Hatch */}
      <Link to="/dashboard" style={{ position: 'absolute', top: '2.5rem', left: 'clamp(1rem, 5vw, 3rem)', display: 'flex', alignItems: 'center', gap: '0.6rem', color: '#6b7a99', textDecoration: 'none', fontWeight: 600, fontSize: '0.9rem', transition: 'color 0.2s', zIndex: 50 }} onMouseEnter={e => e.target.style.color = '#fff'} onMouseLeave={e => e.target.style.color = '#6b7a99'}>
        <ArrowLeft size={16} /> Dashboard
      </Link>

      <div style={{ maxWidth: 800, margin: '0 auto', padding: '0 5%' }}>
        
        {/* Header Content */}
        <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.6rem', background: 'rgba(0, 212, 255, 0.1)', color: '#00d4ff', padding: '0.4rem 1rem', borderRadius: 100, fontSize: '0.8rem', fontWeight: 700, letterSpacing: '0.1em', marginBottom: '1.5rem', border: '1px solid rgba(0, 212, 255, 0.3)' }}>
            <Sparkles size={14} /> THE CAREER ARCHITECT
          </div>
          <h1 style={{ fontSize: 'clamp(2.5rem, 5vw, 4rem)', fontWeight: 800, fontFamily: 'Syne, sans-serif', color: '#fff', lineHeight: 1.1, marginBottom: '1rem' }}>
            Map Your <span className="gradient-text">Future</span>.
          </h1>
          <p style={{ color: '#8796b5', fontSize: '1.1rem', maxWidth: 600, margin: '0 auto' }}>
            Tell our AI exactly what tech role you want to achieve, and it will construct a personalized 5-step learning timeline to get you hired.
          </p>
        </div>

        {/* Input Form */}
        <form onSubmit={generateSyllabus} className="animate-fade-up" style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', marginBottom: '4rem', zIndex: 10 }}>
          <div style={{ flex: 1, position: 'relative', minWidth: 'min(100%, 320px)' }}>
            <div style={{ position: 'absolute', left: '1.5rem', top: '50%', transform: 'translateY(-50%)', color: '#00d4ff' }}><Briefcase size={22} /></div>
            <input 
              value={prompt} 
              onChange={e => setPrompt(e.target.value)}
              disabled={loading}
              placeholder="e.g. Senior Machine Learning Engineer at OpenAI"
              style={{ width: '100%', padding: '1.5rem 1.5rem 1.5rem 4rem', fontSize: '1.05rem', background: 'rgba(8, 15, 31, 0.6)', border: '1px solid rgba(0,212,255,0.3)', borderRadius: 16, color: '#fff', outline: 'none', boxShadow: '0 10px 40px rgba(0,0,0,0.5), inset 0 0 20px rgba(0,212,255,0.05)', transition: 'all 0.3s' }}
              onFocus={e => e.target.style.borderColor = '#00d4ff'}
              onBlur={e => e.target.style.borderColor = 'rgba(0,212,255,0.3)'}
            />
          </div>
          <button type="submit" disabled={loading || !prompt.trim()} className="btn-primary hover-glow" style={{ padding: '0 2.5rem', border: 'none', background: 'linear-gradient(135deg,#00d4ff,#7c3aed)', borderRadius: 16, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.8rem', fontWeight: 800, fontSize: '1.1rem', minHeight: '64px', flexShrink: 0, opacity: (loading||!prompt.trim()) ? 0.5 : 1 }}>
            {loading ? 'Routing...' : 'Generate Roadmap'} <ArrowRight size={18} />
          </button>
        </form>

        {/* Skeleton Loading State */}
        {loading && (
          <div style={{ animation: 'pulse 1.5s infinite', maxWidth: 600, margin: '0 auto' }}>
            <h3 style={{ color: '#00d4ff', fontFamily: 'Syne, sans-serif', fontSize: '1.2rem', fontWeight: 700, marginBottom: '2.5rem', textAlign: 'center' }}>Synthesizing Timeline...</h3>
            {[1,2,3].map(i => (
              <div key={i} style={{ display: 'flex', gap: '2rem', marginBottom: '2.5rem' }}>
                <div style={{ width: 64, height: 64, borderRadius: '50%', background: 'rgba(255,255,255,0.05)', flexShrink: 0 }} />
                <div style={{ flex: 1, height: 120, borderRadius: 16, background: 'rgba(255,255,255,0.03)' }} />
              </div>
            ))}
          </div>
        )}

        {/* Generated Timeline rendered conditionally */}
        {roadmap && !loading && (
          <div className="animate-fade-up" style={{ position: 'relative', marginTop: '2rem' }}>
            {/* The vertical connector line */}
            <div style={{ position: 'absolute', top: 30, bottom: 30, left: 32, width: 2, background: 'linear-gradient(to bottom, transparent, rgba(0,212,255,0.3), transparent)' }}></div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem' }}>
              {roadmap.map((step, index) => {
                const isNeuralPathClass = step.title.toLowerCase().includes('neuralpath') || step.description.toLowerCase().includes('neuralpath') || step.description.toLowerCase().includes('bootcamp') || step.description.toLowerCase().includes('offline')
                return (
                  <div key={index} style={{ display: 'flex', gap: '2rem', position: 'relative', opacity: 0, animation: `fadeUp 0.6s ease forwards ${index * 0.15}s` }}>
                    
                    {/* Timeline Node */}
                    <div style={{ width: 64, height: 64, borderRadius: '50%', background: isNeuralPathClass ? 'rgba(6,255,165,0.1)' : 'rgba(8,15,31,0.9)', border: `2px solid ${isNeuralPathClass ? '#06ffa5' : '#00d4ff'}`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, zIndex: 2, boxShadow: `0 0 20px ${isNeuralPathClass ? 'rgba(6,255,165,0.3)' : 'rgba(0,212,255,0.2)'}` }}>
                      {isNeuralPathClass ? <CheckCircle2 color="#06ffa5" size={24} /> : <span style={{ color: '#00d4ff', fontWeight: 800, fontFamily: 'Syne, sans-serif', fontSize: '1.2rem' }}>{step.step || (index+1)}</span>}
                    </div>

                    {/* Content Card */}
                    <div className="card hover-glow" style={{ flex: 1, padding: '2.5rem', background: isNeuralPathClass ? 'rgba(6,255,165,0.03)' : 'rgba(8,15,31,0.6)', border: `1px solid ${isNeuralPathClass ? 'rgba(6,255,165,0.2)' : 'rgba(255,255,255,0.05)'}` }}>
                      <div style={{ display: 'inline-block', padding: '0.4rem 1rem', background: 'rgba(255,255,255,0.05)', borderRadius: 100, fontSize: '0.75rem', color: '#a3b5d8', fontWeight: 700, letterSpacing: '0.05em', marginBottom: '1.2rem', textTransform: 'uppercase' }}>
                        {step.duration}
                      </div>
                      <h3 style={{ fontSize: '1.4rem', fontWeight: 800, color: '#fff', marginBottom: '1rem', fontFamily: 'Syne, sans-serif' }}>{step.title}</h3>
                      <p style={{ color: '#8796b5', fontSize: '1.05rem', lineHeight: 1.7 }}>{step.description}</p>
                      
                      {isNeuralPathClass && (
                        <div style={{ marginTop: '1.5rem', paddingTop: '1.5rem', borderTop: '1px solid rgba(6,255,165,0.1)' }}>
                          <Link to="/courses" className="btn-primary" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.6rem', padding: '0.7rem 1.4rem', fontSize: '0.9rem', background: '#06ffa5', color: '#000', boxShadow: '0 0 20px rgba(6,255,165,0.4)', textDecoration: 'none', fontWeight: 700 }}>
                            <Sparkles size={16} /> Book Benchmark Offline Class
                          </Link>
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
              <div className="animate-fade-up" style={{ marginTop: '2rem', display: 'flex', justifyContent: 'center', gap: '1.5rem', animationDelay: '1s' }}>
                <button
                  onClick={shareToLinkedIn}
                  className="btn-primary hover-glow"
                  style={{ background: '#0077b5', border: '1px solid #00a0dc', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Linkedin size={16} /> Share to LinkedIn
                </button>
                <button
                  onClick={downloadTimeline}
                  className="btn-ghost"
                  style={{ border: '1px solid rgba(255,255,255,0.2)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Download size={16} /> Download as PDF
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
